---
env:
  global:
    - CC_TEST_REPORTER_ID: 2a1b1e2dd004e80f0a6522359fa16b9492b2d44f4f0a86dc36131aa4a9ec8044
sudo: false
language: ruby
cache: bundler
rvm:
- 2.2.9
- 2.3.1
- 2.3.3
- 2.4.3
- 2.5.0
- 2.5.1
before_install: gem install bundler -v 1.16.5
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
