#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH << File.expand_path('../lib', __dir__)
require 'cloud_flare/dynamic_dns'

CloudFlare::DynamicDNS::Runner.new(path: './cloudflare-dynamic-dns.conf').execute
